### ISSUE TITLE
nuget版本无法执行，提示The plugin collection does not contain a plugin

### ISSUE THREAD

**Issue by 102709805** [AIDotNet/GraphRag.Net#16]
nuget版本提示错误：
System.Collections.Generic.KeyNotFoundException: The plugin collection does not contain a plugin and/or function with the specified names. Plugin name - 'graph', function name - 'create'.
   at Microsoft.SemanticKernel.KernelPluginExtensions.GetFunction(IReadOnlyKernelPluginCollection plugins, String pluginName, String functionName)
   at GraphRag.Net.Domain.Service.SemanticService.CreateGraphAsync(String input)
   at GraphRag.Net.Domain.Service.GraphService.InsertGraphDataAsync(String index, String input)
System.Collections.Generic.KeyNotFoundException: The plugin collection does not contain a plugin and/or function with the specified names. Plugin name - 'graph', function name - 'create'.
   at Microsoft.SemanticKernel.KernelPluginExtensions.GetFunction(IReadOnlyKernelPluginCollection plugins, String pluginName, String functionName)
   at GraphRag.Net.Domain.Service.SemanticService.CreateGraphAsync(String input)
   at GraphRag.Net.Domain.Service.GraphService.InsertGraphDataAsync(String index, String input)
System.Collections.Generic.KeyNotFoundException: The plugin collection does not contain a plugin and/or function with the specified names. Plugin name - 'graph', function name - 'create'.
   at Microsoft.SemanticKernel.KernelPluginExtensions.GetFunction(IReadOnlyKernelPluginCollection plugins, String pluginName, String functionName)
   at GraphRag.Net.Domain.Service.SemanticService.CreateGraphAsync(String input)
   at GraphRag.Net.Domain.Service.GraphService.InsertGraphDataAsync(String index, String input)
System.Collections.Generic.KeyNotFoundException: The plugin collection does not contain a plugin and/or function with the specified names. Plugin name - 'graph', function name - 'create'.

![image](https://github.com/user-attachments/assets/6bc37bdc-86e2-4d62-b2e2-901940d96bf3)

**Comment by xuzeyu91** [comment]
由于插件在nuget包里输出有问题，你需要把GraphRag.Net.Web项目中的 graphPlugins目录拷贝到你的项目中，并设置：
```
  <ItemGroup>
    <None Include="graphPlugins\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```
这样才能引用到插件

**Comment by 102709805** [comment]
> 由于插件在nuget包里输出有问题，你需要把GraphRag.Net.Web项目中的 graphPlugins目录拷贝到你的项目中，并设置：
> 
> ```
>   <ItemGroup>
>     <None Include="graphPlugins\**">
>       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
>     </None>
>   </ItemGroup>
> ```
> 
> 这样才能引用到插件

这个是在哪个文件中设置

**Comment by xuzeyu91** [comment]
> > 由于插件在nuget包里输出有问题，你需要把GraphRag.Net.Web项目中的 graphPlugins目录拷贝到你的项目中，并设置：
> > 
> > ```
> >   <ItemGroup>
> >     <None Include="graphPlugins\**">
> >       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
> >     </None>
> >   </ItemGroup>
> > ```
> > 
> > 这样才能引用到插件
> 
> 这个是在哪个文件中设置

项目的csproj
